version: "3.9"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todoapi
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: ./.env
    depends_on: 
      - db
    ports:
      - "8080:8080"
    networks:
      - backend
 
networks:
  backend:
    driver: bridge